{"id":"dojochan.js",
"sources":[
	{
		"name":"BoardGroup",
		"extends":"Object",
		"schema":{
			"extends":{"$ref":"../Class/Object"},
			"prototype":{
				},
			"instances":{"$ref":"../BoardGroup/"},
			"description":"A group of boards",
			"properties":{
				"name":{
					"type":"string"
					},
				"boards":{
					"type":"array"
					}
				}
			}
		},
	{
		"name":"Board",
		"extends":"Object",
		"schema":{
			"extends":{"$ref":"../Class/Object"},
			"prototype":{
				},
			"instances":{"$ref":"../Board/"},
			"description":"A discussion board",
			"properties":{
				"title":{
					"type":"string",
					"optional":false
					},
				"url":{
					"type":"string",
					"optional":false
					},
				"description":{
					"type":"string"
					}
				}
			}
		},
	{
		"name":"Thread",
		"extends":"Object",
		"schema":{
			"extends":{"$ref":"../Class/Object"},
			"prototype":{
				},
			"instances":{"$ref":"../Thread/"},
			"description":"A discussion thread on a board",
			"properties":{
				"posts":{
					"type":"array",
					"default":[]
					},
				"lastPost":{
					"type":"integer"
					},
				"board":{
					"type":"object"
					}
				}
			}
		},
	{
		"name":"Post",
		"extends":"Object",
		"schema":{
			"extends":{"$ref":"../Class/Object"},
			"prototype":{
				},
			"instances":{"$ref":"../Post/"},
			"description":"A post in a thread",
			"properties":{
				"name":{
					"type":"string",
					"optional":true
					},
				"email":{
					"type":"string",
					"optional":true
					},
				"tripcode":{
					"type":"string",
					"optional":true
					},
				"nameblock":{
					"type":"string",
					"optional":true
					},
				"subject":{
					"type":"string",
					"optional":true
					},
				"message":{
					"type":"string"
					},
				"file":{
					"type":"object",
					"optional":true
					},
				"thread":{
					"type":"object"
					}
				}
			}
		}]
}